---
title: "Initial data analysis for high school project."
author: "Brandon D. Hoenig"
date: "2024-04-17"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load necessary libraries
```{r}
library(tidyverse)
library(plotly)
```

## Get acquainted with R Studio
```{bash, echo = F}

```

## Introduction to 'directories'
```{r}

```

## How does R work?
```{bash, echo = F}
Objects, Functions, and Arguments

Objects are anything that can have something done to them. 
  Think 'nouns'

Functions are the things doing the doing. 
  Think 'verbs'
  
Arguments are ways to modify what functions can do. 
Think 'adverbs'
```

Making our first objects
```{r}

```

Using our first functions
```{r}

```


## Read in data & make object. 
```{r}
bd_data <- # this line of code assigns a name to the line of code below. 
  read_csv(fil = "output/bd_results_and_environmental_metadata.csv") 
```

## run a model to assess if body mass and length are correlated
```{r}
qplot(data = bd_data, 
      x = body_mass_g, 
      y = body_length_mm, 
      geom = 'point')
```



